### ISSUE TITLE
blackjack assignment for marking 

### ISSUE THREAD

**Issue by charlotteKoch** [charlotteKoch/ICS3U#3]
https://github.com/charlotteKoch/ICS3U/blob/master/Unit%20Four/src/com/bayviewglen/blackjack/BlackjackAssignment.java

**Comment by kevindeslauriers** [comment]
Excellent work - it handles all of the cases very well.

Feedback: You should use no magic numbers and you did.
I would check the formatting of your user output.  Some blank lines to make it easier to read would be helpful.

Overall you code was very organised and read well. It would also help to handle other versions of yes and no.  like y or n.

96%

![image](https://cloud.githubusercontent.com/assets/739858/6135061/83487f44-b133-11e4-8ad7-aa4c022adfd0.png)
